<a href="https://colab.research.google.com/github/Pipickin/Tensorflow/blob/main/TF_API_exapmle/Linear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
class Linear(tf.keras.Model):
  def __init__(self):
    super(Linear, self).__init__()
    self.l1 = tf.keras.layers.Dense(5)

  def call(self, inputs):
    return self.l1(inputs)

In [ ]:
linear = Linear()
inputs1 = tf.Variable([[1.]])
print('output when inp is 1 : {}'.format(linear(inputs1).numpy()))

inputs2 = tf.Variable([[2.]])
print('output when inp is 2 : {}'.format(linear(inputs2).numpy()))

inputs1_2 = tf.Variable([[3.]])
print('output when inp are 1 and 2 : {}'.format(linear(inputs1_2).numpy()))

output when inp is 1 : [[-0.6287761  -0.12758088 -0.54431176  0.30533147  0.22397685]]
output when inp is 2 : [[-1.2575521  -0.25516176 -1.0886235   0.61066294  0.4479537 ]]
output when inp are 1 and 2 : [[-1.8863282  -0.38274264 -1.6329353   0.9159944   0.67193055]]


In [ ]:
x = tf.range(1., 4.)[:, tf.newaxis]
print(linear(x).numpy())

[[-0.6287761  -0.12758088 -0.54431176  0.30533147  0.22397685]
 [-1.2575521  -0.25516176 -1.0886235   0.61066294  0.4479537 ]
 [-1.8863282  -0.38274264 -1.6329353   0.9159944   0.67193055]]


In [ ]:
def toy_dataset():
  inputs = tf.range(10.)[:, tf.newaxis]
  outputs = 5*inputs + tf.range(5.)[tf.newaxis, :]
  return 

In [ ]:
outputs

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.],
       [25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34.],
       [35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44.],
       [45., 46., 47., 48., 49.]], dtype=float32)>