<a href="https://colab.research.google.com/github/Pipickin/Tensorflow/blob/main/TF_API_exapmle/Work_witf_tf_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np
import collections

# Define

In [ ]:
train, test = tf.keras.datasets.mnist.load_data()
mnist_x, mnist_y = train

mnist_ds = tf.data.Dataset.from_tensor_slices(mnist_x)

print(mnist_x.shape)
print(mnist_ds)

11493376/11490434 [==============================] - 0s 0us/step
(60000, 28, 28)
<TensorSliceDataset shapes: (28, 28), types: tf.uint8>


In [ ]:
a = np.array([[[1,1,1],[2,2,2]],
              [[3,3,3],[4,4,4]]])
print(a.shape)

a_ds = tf.data.Dataset.from_tensor_slices(a)
a_np = list(a_ds.as_numpy_iterator())
print(a_np)

a_ds_shufled = a_ds.shuffle(5, reshuffle_each_iteration=True) 
a_np_shufled = list(a_ds_shufled.as_numpy_iterator())
print(a_np_shufled)

(2, 2, 3)
[array([[1, 1, 1],
       [2, 2, 2]]), array([[3, 3, 3],
       [4, 4, 4]])]
[array([[1, 1, 1],
       [2, 2, 2]]), array([[3, 3, 3],
       [4, 4, 4]])]


In [ ]:
a_ds_shufled_repeated = a_ds_shufled.repeat(2)
print(list(a_ds_shufled_repeated.as_numpy_iterator()))

[array([[3, 3, 3],
       [4, 4, 4]]), array([[1, 1, 1],
       [2, 2, 2]]), array([[3, 3, 3],
       [4, 4, 4]]), array([[1, 1, 1],
       [2, 2, 2]])]


In [ ]:
a_ds_shufled_repeated_batched = a_ds_shufled_repeated.batch(2)
print(list(a_ds_shufled_repeated_batched.as_numpy_iterator()))
print(a_ds_shufled_repeated_batched)

[array([[[3, 3, 3],
        [4, 4, 4]],

       [[1, 1, 1],
        [2, 2, 2]]]), array([[[3, 3, 3],
        [4, 4, 4]],

       [[1, 1, 1],
        [2, 2, 2]]])]
<BatchDataset shapes: (None, 2, 3), types: tf.int64>


In [ ]:
a_ds_shufled_repeated_batched = a_ds_shufled_repeated.batch(3)
print(list(a_ds_shufled_repeated_batched.as_numpy_iterator()))
print(a_ds_shufled_repeated_batched)

[array([[[3, 3, 3],
        [4, 4, 4]],

       [[1, 1, 1],
        [2, 2, 2]],

       [[1, 1, 1],
        [2, 2, 2]]]), array([[[3, 3, 3],
        [4, 4, 4]]])]
<BatchDataset shapes: (None, 2, 3), types: tf.int64>


In [ ]:
a_ds_shufled_repeated_batched = a_ds_shufled_repeated.batch(4)
print(list(a_ds_shufled_repeated_batched.as_numpy_iterator()))
tf.print(a_ds_shufled_repeated_batched)

[array([[[3, 3, 3],
        [4, 4, 4]],

       [[1, 1, 1],
        [2, 2, 2]],

       [[3, 3, 3],
        [4, 4, 4]],

       [[1, 1, 1],
        [2, 2, 2]]])]
<BatchDataset shapes: (None, 2, 3), types: tf.int64>


In [ ]:
b = a_ds_shufled_repeated_batched
b = b.map(lambda x: x*2)

In [ ]:
print(list(b.as_numpy_iterator()))

[array([[[6, 6, 6],
        [8, 8, 8]],

       [[2, 2, 2],
        [4, 4, 4]],

       [[6, 6, 6],
        [8, 8, 8]],

       [[2, 2, 2],
        [4, 4, 4]]])]


In [ ]:
dict_a = {'key1': [1,2],
          'key2': 3}
Point = collections.namedtuple('Point', ['x', 'y'])
e = Point(12, 42)
f = tf.data.Dataset.range(10)
print(list(f.as_numpy_iterator()))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


# Apply

In [ ]:
def square_of_positive(ds):
  ds1 = ds.filter(lambda x: x>0)
  return ds1.map(lambda x: x**2)


dataset = tf.data.Dataset.range(-5, 5)
dataset_map = dataset.map(lambda x: x>0)
dataset = dataset.apply(square_of_positive)

print(list(dataset_map.as_numpy_iterator()))
print(list(dataset.as_numpy_iterator()))

[False, False, False, False, False, False, True, True, True, True]
[1, 4, 9, 16]


In [ ]:
dataset = dataset.map(lambda x: x*5)
list(dataset.as_numpy_iterator())

[5, 20, 45, 80]

In [ ]:
dataset = tf.data.Dataset.from_tensor_slices({'a': ([1, 2], [3, 4]),
                                              'b': [7, 8]})
list(dataset.as_numpy_iterator())

[{'a': (1, 3), 'b': 7}, {'a': (2, 4), 'b': 8}]

# Batch and shufle

In [ ]:
dataset = tf.data.Dataset.range(1, 20)
dataset = dataset.batch(3, drop_remainder=True)
list(dataset.as_numpy_iterator())

[array([1, 2, 3]),
 array([4, 5, 6]),
 array([7, 8, 9]),
 array([10, 11, 12]),
 array([13, 14, 15]),
 array([16, 17, 18])]